### ISSUE TITLE
SyntaxError upon importing

### ISSUE THREAD

**Issue by david-pettifor-nd** [YaleDHLab/lexis-nexis-wsk#17]
Simply trying:
`from wsk import WSK`

Gives the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/wsk/__init__.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/wsk-0.1.7-py2.7.egg/wsk/wsk.py", line 171
SyntaxError: 'return' with argument inside generator`

Library was installed using pip, version is 0.1.7.

**Comment by david-pettifor-nd** [comment]
Note: this only occurs in Python 2.7.  When installed and imported in Python 3.5, no error occurs.

**Comment by duhaime** [comment]
@david-pettifor-nd Thanks for the heads up on this! I just pushed 0.1.8 to pypi, which should resolve this. If you have a moment to try `pip install wsk -U`, can I ask if you still have troubles with 2.7? If so I'm happy to troubleshoot.

**Comment by david-pettifor-nd** [comment]
That fixed it!  I had to install the other requirements (requests and lxml) from a vanilla base install of Ubuntu but I was able to import the library and get the authentication working.

Thanks!

**Comment by duhaime** [comment]
Awesome! Thanks again for following up on this. If you end up working with the WSK servers extensively, feel free to write me. The team I'm working with in the Yale library have been talking to a number of other institutions building wrappers around the WSK servers; I'd be happy to discuss!

**Comment by david-pettifor-nd** [comment]
Thanks!  We're currently prospecting a potential project that would heavily
rely on their API.  The software stack at the moment would include a Django
web interface with possible job dispatching to collect/compress results
based on a more generalized search query (in comparison to their already
provided web searching interface).  I was thrilled to see a Python wrapper
already done for this, of course!  But depending on the project's needs, I
may need to fork it and add to it where we find it necessary.  I'll do my
best to keep it as generic as possible (so it can later be re-used by other
institutions), and of course I would be happy to work with you and your
team to provide anything you may find helpful!

David Pettifor
*Senior Research Programmer*
Center for Research Computing


*e: *David.W.Pettifor.1@nd.edu
*p: (574) 631-*3656
*slack: dpettifo*

**Comment by duhaime** [comment]
@david-pettifor-nd Phenomenal news! We'd be happy to merge PR's if you want to send them. I'm a huge fan of ND's CRC team, so if there's anything I can do to assist, please just say the word.
